server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push   # apuntamos al contenedor Loki dentro de docker-compose

scrape_configs:
  - job_name: log-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: log-server
          __path__: /var/log/central-logs/*.log
